In [ ]:
#Creating Array Command

In [1]:
import numpy as np

In [2]:
a = np.array(0)

In [3]:
a

array(0)

In [5]:
b = np.array([ 1 , 2 , 3])

In [6]:
b

array([1, 2, 3])

In [8]:
c = np.array([[1 , 2] , [3 , 4]])

In [9]:
c

array([[1, 2],
       [3, 4]])

In [14]:
c.shape

(2, 2)

In [16]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [17]:
np.ones((1 , 4))

array([[1., 1., 1., 1.]])

In [21]:
d = np.arange(0,50,3)

In [22]:
d

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48])

In [23]:
d.shape

(17,)

In [26]:
e = np.random.rand(50 , 1)

In [30]:
e

array([[0.0915978 ],
       [0.02141249],
       [0.87608296],
       [0.5358997 ],
       [0.83064202],
       [0.66162854],
       [0.69594882],
       [0.05378625],
       [0.07585299],
       [0.32600504],
       [0.65369911],
       [0.0183536 ],
       [0.10539003],
       [0.36793759],
       [0.5033821 ],
       [0.30276762],
       [0.74041817],
       [0.03266843],
       [0.49117854],
       [0.04141961],
       [0.47923737],
       [0.85765548],
       [0.44116108],
       [0.36628678],
       [0.16170972],
       [0.50980587],
       [0.34889796],
       [0.20501431],
       [0.74304819],
       [0.44906392],
       [0.15721965],
       [0.96802387],
       [0.48138417],
       [0.01981335],
       [0.22402165],
       [0.71551081],
       [0.04095265],
       [0.71537371],
       [0.96943497],
       [0.42779012],
       [0.9779997 ],
       [0.06145929],
       [0.88202584],
       [0.55841767],
       [0.93005628],
       [0.15535824],
       [0.18701803],
       [0.478

In [33]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
np.random.randint(0 , 2500)

1411

In [36]:
#inspecting properties command

In [37]:
import numpy as no

In [38]:
a = np.arange(0 , 100 , 2)

In [42]:
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [43]:
a.size

50

In [44]:
a.shape

(50,)

In [46]:
a.dtype

dtype('int32')

In [47]:
a.astype(float)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24.,
       26., 28., 30., 32., 34., 36., 38., 40., 42., 44., 46., 48., 50.,
       52., 54., 56., 58., 60., 62., 64., 66., 68., 70., 72., 74., 76.,
       78., 80., 82., 84., 86., 88., 90., 92., 94., 96., 98.])

In [49]:
a.tolist()

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98]

In [50]:
#copying  , sorting and reshape command

In [51]:
import numpy as np

In [52]:
a = np.arange(0 , 100 , 2)

In [53]:
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [54]:
c = np.copy(a)

In [55]:
c

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [56]:
a.dtype

dtype('int32')

In [57]:
a.view(float)

array([4.24399158e-314, 1.27319747e-313, 2.12199579e-313, 2.97079411e-313,
       3.81959242e-313, 4.66839074e-313, 5.51718906e-313, 6.36598737e-313,
       7.21478569e-313, 8.06358401e-313, 8.91238232e-313, 9.76118064e-313,
       1.06099790e-312, 1.14587773e-312, 1.23075756e-312, 1.31563739e-312,
       1.40051722e-312, 1.48539705e-312, 1.57027689e-312, 1.65515672e-312,
       1.74003655e-312, 1.82491638e-312, 1.90979621e-312, 1.99467604e-312,
       2.07955588e-312])

In [58]:
d = np.array([[1 , 2 , 3 , 4]])

In [59]:
d 

array([[1, 2, 3, 4]])

In [60]:
d.shape

(1, 4)

In [61]:
d.flatten()

array([1, 2, 3, 4])

In [63]:
d.T

array([[1],
       [2],
       [3],
       [4]])

In [64]:
d.reshape(4 , 1)

array([[1],
       [2],
       [3],
       [4]])

In [65]:
#Adding AND removing commands

In [66]:
a = np.arange( 1 , 100 , 2)

In [67]:
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [69]:
np.append(a , 100)

array([  1,   3,   5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,
        27,  29,  31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97,  99, 100])

In [70]:
np.delete(a , 1 , axis = 0)

array([ 1,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
       37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69,
       71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [71]:
#Indexing , Slicing and Subsetting Commands

In [72]:
a[0]

1

In [74]:
a[49]

99

In [75]:
a[0:10]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [77]:
a[-1]

99

In [78]:
a[:19]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37])

In [79]:
a[1:]

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
       37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69,
       71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [80]:
#Sclar Math command

In [82]:
a = np.arange(0 , 20 , 2)

In [83]:
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [84]:
np.add(a , 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [85]:
np.subtract(a, 1)

array([-1,  1,  3,  5,  7,  9, 11, 13, 15, 17])

In [86]:
np.multiply(a , 2)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [87]:
np.divide(a,2)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [88]:
np.power(a , 2)

array([  0,   4,  16,  36,  64, 100, 144, 196, 256, 324], dtype=int32)

In [ ]:
#vector Math commands

In [89]:
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [91]:
b = np.arange(20 , 40 , 2)

In [92]:
b

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [93]:
np.add(a, b)

array([20, 24, 28, 32, 36, 40, 44, 48, 52, 56])

In [94]:
np.subtract(a , b)

array([-20, -20, -20, -20, -20, -20, -20, -20, -20, -20])

In [95]:
np.multiply(a, b)

array([  0,  44,  96, 156, 224, 300, 384, 476, 576, 684])

In [97]:
np.divide(a, b)

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])

In [98]:
#statistics command

In [100]:
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [101]:
a.sum()

90

In [102]:
a.mean()

9.0

In [103]:
a.max()

18

In [104]:
np.var(a)

33.0

In [105]:
np.std(a)

5.744562646538029

In [106]:
#combining and splitting commands

In [107]:
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [108]:
b

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [110]:
np.concatenate((a , b) , axis = 0)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [113]:
np.split(a,5)

[array([0, 2]),
 array([4, 6]),
 array([ 8, 10]),
 array([12, 14]),
 array([16, 18])]

In [114]:
import numpy as np

In [115]:
arr = np.array([ 1 , 2 , 3 , 4 , 5])
print(arr)

[1 2 3 4 5]


In [117]:
arr_2d = np.array([[1,2,2],[4,5,6]])
print(arr_2d)

[[1 2 2]
 [4 5 6]]


In [118]:
my_list = [1 , 2 , 3 , 4]
type(my_list)

list

In [119]:
arr = np.array(my_list)
print(arr)

[1 2 3 4]


In [120]:
arr

array([1, 2, 3, 4])

In [121]:
type(arr)

numpy.ndarray

In [122]:
arr.ndim

1

In [ ]:
#creating array witk Zores And Ones

In [128]:
import numpy as np

zeros = np.zeros((2, 3), dtype=int)
print("Array of Zeros:")
print(zeros)


Array of Zeros:
[[0 0 0]
 [0 0 0]]


In [130]:
ones = np.ones((3,2))
print("Array of ones")
print(ones)

Array of ones
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [131]:
range_array = np.arange(10)
print("Array with a range of valuess:")
print(range_array)

Array with a range of valuess:
[0 1 2 3 4 5 6 7 8 9]


In [132]:
range_array_step = np.arange(1 ,10 , 2)
print("Array with a range of valuess:")
print(range_array_step)

Array with a range of valuess:
[1 3 5 7 9]


In [135]:
Vector_row = np.array([1 , 2 , 3])

In [136]:
Vector_row

array([1, 2, 3])

In [137]:
print(Vector_row[:2])

[1 2]


In [138]:
print(Vector_row[2])

3


In [139]:
Vector_column = np.array([[1] , [2] , [3]])

In [140]:
Vector_column

array([[1],
       [2],
       [3]])

In [142]:
Vector_column.ndim

2

In [143]:
print(Vector_column.size)

3


In [146]:
matrix = np.array([[1,2,3],[4,5,6],[5,9,0],[9,8,10,],[5,4,3]])
matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 5,  9,  0],
       [ 9,  8, 10],
       [ 5,  4,  3]])

In [147]:
print(matrix[4: , 1:])

[[4 3]]


In [148]:
matrix[4 , -2:]

array([4, 3])

In [149]:
print(matrix.shape)

(5, 3)


In [150]:
print(matrix[ : , 1:2])

[[2]
 [5]
 [9]
 [8]
 [4]]


In [151]:
print(matrix[2:4 , 0:2])

[[5 9]
 [9 8]]


In [152]:
print(matrix[3:4 , 1:3])

[[ 8 10]]


In [153]:
print(matrix.size)

15


In [154]:
print(np.max(matrix))

10


In [155]:
print(np.min(matrix))

0


In [156]:
print(np.max(matrix , axis = 0))

[ 9  9 10]


In [157]:
print(np.max(matrix , axis = 1))

[ 3  6  9 10  5]


In [158]:
print(np.mean(matrix , axis = 1))

[2.         5.         4.66666667 9.         4.        ]


In [159]:
print(matrix.reshape(1 , 15))

[[ 1  2  3  4  5  6  5  9  0  9  8 10  5  4  3]]


In [160]:
matrix_1 = np.array([[1 , 2 , 3] , [ 6 , 5 ,6] , [ 7 , 7 , 9]])

In [162]:
matrix_1

array([[1, 2, 3],
       [6, 5, 6],
       [7, 7, 9]])

In [163]:
matrix_2 = np.array([[7,8,9] , [4,5,6] , [1,2,3]])

In [164]:
matrix_2

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [167]:
print(np.add(matrix_1 , matrix_2))

[[ 8 10 12]
 [10 10 12]
 [ 8  9 12]]


In [168]:
matrix_1 + matrix_2

array([[ 8, 10, 12],
       [10, 10, 12],
       [ 8,  9, 12]])

In [169]:
print(np.subtract(matrix_1 , matrix_2))

[[-6 -6 -6]
 [ 2  0  0]
 [ 6  5  6]]


In [170]:
matrix_1 - matrix_2

array([[-6, -6, -6],
       [ 2,  0,  0],
       [ 6,  5,  6]])

In [171]:
print(matrix_1 * matrix_2)

[[ 7 16 27]
 [24 25 36]
 [ 7 14 27]]


In [2]:
import numpy as np

In [3]:
x = np.array([[1 ,2],[3,4]])
y = np.array([[12 , 30]])

In [4]:
x

array([[1, 2],
       [3, 4]])

In [5]:
y

array([[12, 30]])

In [7]:
z = np.concatenate((x , y) , axis = 0)

In [179]:
z

array([[ 1,  2],
       [ 3,  4],
       [12, 30]])

In [184]:
x = np.array([[1,2] , [3 , 4]])
y = np.array([[12,30]])
z = np.concatenate((x,y.T) , axis = 1)

In [185]:
z

array([[ 1,  2, 12],
       [ 3,  4, 30]])

In [187]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [189]:
a = np.zeros((6 ,) , dtype = int)
a

array([0, 0, 0, 0, 0, 0])

In [190]:
a = np.zeros((6 , 2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [192]:
a = np.ones((6 , 1) ,dtype = int)
a

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [193]:
size = 5

In [196]:
idt_matrix = np.zeros((size , size) , dtype = int)
idt_matrix

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [197]:
np.fill_diagonal(idt_matrix , 5)

In [198]:
print(idt_matrix)

[[5 0 0 0 0]
 [0 5 0 0 0]
 [0 0 5 0 0]
 [0 0 0 5 0]
 [0 0 0 0 5]]


In [202]:
a = np.array([[ 1 , 4 , 7] , [ 2 , 5 , 8] , [ 3 , 6 , 9]])
b = a.flatten()
b

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [203]:
a

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [204]:
b.ndim

1

In [205]:
a.ndim

2

In [208]:
a = np.unique([ 1 , 2 , 3 , 4 , 5 ,6 , 2 , 4 , 9 , 9 ,0])

In [209]:
a

array([0, 1, 2, 3, 4, 5, 6, 9])

In [210]:
a = np.array([[ 1 , 1 , 0 ] , [ 1 , 1 , 0] , [ 2 , 3 , 4 ] , [5 , 9 , 8] , [ 2 , 3 , 4]])

In [211]:
b = np.unique( a , axis = 0)

In [212]:
b

array([[1, 1, 0],
       [2, 3, 4],
       [5, 9, 8]])

In [213]:
a

array([[1, 1, 0],
       [1, 1, 0],
       [2, 3, 4],
       [5, 9, 8],
       [2, 3, 4]])

In [214]:
a = np.array([[ 1 , 1 , 5] , [ 1 , 1 ,0] , [ 2 , 2 , 4] , [ 5 , 5 , 8] , [ 2 , 2 , 4]])

In [215]:
a

array([[1, 1, 5],
       [1, 1, 0],
       [2, 2, 4],
       [5, 5, 8],
       [2, 2, 4]])

In [216]:
 b = np.unique(a , axis = 0)

In [217]:
b

array([[1, 1, 0],
       [1, 1, 5],
       [2, 2, 4],
       [5, 5, 8]])

In [220]:
a  = np.random.rand(5 , 2)
a

array([[0.80291247, 0.92719285],
       [0.89958326, 0.7680686 ],
       [0.26645844, 0.54771744],
       [0.07396307, 0.5637787 ],
       [0.09969774, 0.23732975]])

In [223]:
a = np.random.randint( 5 ,10 , size = 15)
a

array([9, 5, 7, 7, 5, 5, 7, 9, 6, 7, 5, 5, 6, 5, 5])

In [225]:
a = np.random.randint(179 , size = (5 ,3))

In [226]:
a

array([[174,  58, 100],
       [163,  54,  35],
       [ 13, 141,  29],
       [ 83,  41,  73],
       [ 31,  14, 173]])

In [229]:
arr = [0.23 , 0.09 , 1.2 , 1.24 , 9.99 , 101.01]
r_arr = np.ceil(arr)
r_arr

array([  1.,   1.,   2.,   2.,  10., 102.])

In [230]:
arr = [0.23 , 0.09 , 1.2 , 1.24 , 9.99 , 101.01]
r_arr = np.floor(arr)
r_arr

array([  0.,   0.,   1.,   1.,   9., 101.])

In [232]:
arr = [0.23 , 0.09 , 1.2 , 1.24 , 9.99 , 101.01]
r_arr = np.round(arr)
r_arr

array([  0.,   0.,   1.,   1.,  10., 101.])

In [233]:
 b = np.array([12 , 90 , 380 , 12 , 211])
print(np.where(b>12))
a = np.where(b>12)

(array([1, 2, 4], dtype=int64),)


In [234]:
a1 = b[a]
a1

array([ 90, 380, 211])

In [4]:
import numpy as np
npv = np.random.randint(10 , size = 10)
npv

array([3, 9, 9, 1, 6, 4, 9, 8, 7, 5])

In [5]:
npm = npv.reshape(2 , 5 )
npm

array([[3, 9, 9, 1, 6],
       [4, 9, 8, 7, 5]])

In [6]:
npm[0,3]

1

In [7]:
npm[ 1 ,2]

8

In [8]:
npm[0:1 , 1:3]

array([[9, 9]])

In [9]:
npm[1:2 , 0:2]

array([[4, 9]])

In [10]:
lst = [[110 , 90 , 80] , [70 , 60 , 110] , [30 , 10 , 20] , [50 , 40 , 110]]

In [11]:
npm = np.array(lst)

In [12]:
npm

array([[110,  90,  80],
       [ 70,  60, 110],
       [ 30,  10,  20],
       [ 50,  40, 110]])

In [13]:
npm.sum(axis = 1)

array([280, 240,  60, 200])

In [15]:
npm.sum(axis = 0)

array([260, 200, 320])

In [16]:
lst = [[110 , 90 , 80] , [70 , 60 , 110] , [30 , 10 , 20] , [50 , 40 , 110]]
npm = np.array(lst)
npm

array([[110,  90,  80],
       [ 70,  60, 110],
       [ 30,  10,  20],
       [ 50,  40, 110]])

In [19]:
lst2= [[110 , 90 , 80] , [70 , 60 , 110] , [30 , 10 , 20] , [50 , 40 , 0]]
npm1 = np.array(lst)
npm1

array([[110,  90,  80],
       [ 70,  60, 110],
       [ 30,  10,  20],
       [ 50,  40, 110]])

In [20]:
npm3 = npm/npm1
npm3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
lst = [[110 , 90 , 80] , [70 , 60 , 110] , [30 , 10 , 20] , [50 , 40 , 110]]
npm = np.array(lst)
npm

array([[110,  90,  80],
       [ 70,  60, 110],
       [ 30,  10,  20],
       [ 50,  40, 110]])

In [23]:
npm[: , :] = 50
npm

array([[50, 50, 50],
       [50, 50, 50],
       [50, 50, 50],
       [50, 50, 50]])

In [30]:
npm[0,1] = 500
npm

array([[ 50, 500, 500],
       [ 50,  50,  50],
       [ 50,  50, 500],
       [ 50,  50,  50]])

In [31]:
A = np.matrix([[1 , 3 , 4] , [4 , 0 , 2]])
A

matrix([[1, 3, 4],
        [4, 0, 2]])

In [32]:
B = np.matrix([[1 , 3] , [0 , 1] , [5 , 2]])
B

matrix([[1, 3],
        [0, 1],
        [5, 2]])

In [33]:
C = A * B
C

matrix([[21, 14],
        [14, 16]])

In [38]:
A = np.matrix([[5 , 3 , 2] , [ 4 , 0 , 1] , [1 , 0 , 1]])
A

matrix([[5, 3, 2],
        [4, 0, 1],
        [1, 0, 1]])

In [39]:
A.T

matrix([[5, 4, 1],
        [3, 0, 0],
        [2, 1, 1]])

In [40]:
print ( " Trace of A:" , np.trace(A))

 Trace of A: 6
